name: Deploy Static Site

on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Static Site
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/dev.packetloss.com.br
          git pull